# Implementasi Naive Bayes

Naive Bayes adalah metode yang cocok untuk klasifikasi biner dan multiclass. Metode yang juga dikenal sebagai Naive Bayes Classifier ini menerapkan teknik supervised klasifikasi objek di masa depan dengan menetapkan label kelas ke instance/catatan menggunakan probabilitas bersyarat. Probabilitas bersyarat adalah ukuran peluang suatu peristiwa yang terjadi berdasarkan peristiwa lain yang telah (dengan asumsi, praduga, pernyataan, atau terbukti) terjadi. 

## Data yang digunakan

*   Dataset [Iris](https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv)

*   Excel [Hitung Manual Naive Bayes](https://docs.google.com/spreadsheets/d/1fKfYh3BZlke5uELaMNS31ZCUDNLnsUAx/edit?usp=sharing&ouid=112136363283441156113&rtpof=true&sd=true)

In [43]:
from sklearn.model_selection import train_test_split #memecah antara datatraining dan datatest

In [44]:
# mengimpor paket pandas kemudian diberi nama alias pd
import pandas as pd
# mengimpor paket numpy kemudian diberi nama alias np
import numpy as np
# untuk menghilangkan warning
import warnings
warnings.filterwarnings('ignore', category=UserWarning, append=True)

In [45]:
# mengimpor library yang dibutuhkan
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [46]:
# membaca dataset csv dari url
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
data = pd.read_csv(url)

In [47]:
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [48]:
data.shape

(150, 5)

### Hitung Data

*   Pisahkan kolom "variety" dari *dataframe*
*   Ambil kolom "variety" sebagai target kolom untuk kategori kelas
*   Pisahkan data latih dengan data tes


```
# data latih (nilai data)
X_train 

# data tes (nilai data)
X_test 

# data latih (kelas data)
y_train

# data tes (kelas data)
y_test
```





In [49]:
# membuat dataframe dengan data training tanpa label kelas
X = data.drop(columns=["variety"])#Mengecek apakah label kelas sudah terhapus
X.head()

sepal.length  sepal.width  petal.length  petal.width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [50]:
# persentase jumlah data test
persentase_test_data = 0.3

In [51]:
# target terpisah

# nilai
X=data.iloc[:,0:4].values

# kelas
y=data.iloc[:,4].values

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = persentase_test_data, random_state=0)

In [53]:
# penggolongan
gaussian = GaussianNB()
# 
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Konfusi Matrix\n',cm)
print('Akurasi_Naive Bayes: %.3f' %accuracy)
print('Ketepatan_Naive Bayes: %.3f' %precision)
print('Recall_Naive Bayes: %.3f' %recall)
print('f1-score_random_Forest : %.3f' %f1)

Konfusi Matrix
 [[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
Akurasi_Naive Bayes: 1.000
Ketepatan_Naive Bayes: 1.000
Recall_Naive Bayes: 1.000
f1-score_random_Forest : 1.000


In [54]:
clf = GaussianNB()
clf.fit(X, y)
clf_pf = GaussianNB()
clf_pf.partial_fit(X, y, np.unique(y))

GaussianNB()

In [55]:
# uji coba dengan data [5.5, 3, 5, 2.2]
print(clf_pf.predict([[5.5, 3, 5, 2.2]]))

['Virginica']


In [56]:
# uji coba dengan data [4, 3, 5, 1.2]
print(clf_pf.predict([[4, 3, 5, 1.2]]))

['Versicolor']
